### ISSUE TITLE
Issue using > markup button 

### ISSUE THREAD

**Issue by sophlew** [CoEDL/nyingarn-workspace#165]
Using the > markup button in the transcription item/page ATSIQLdHolmer1988-033 has given this error **This page contains the following errors:error on line 20 at column 42: Entity 'rt' not defined**

Background: The Workspace identified the TEI XML error in item ATSIQLdHolmer1988. I went to the page and updated the transcription text with the > mark up button; however, this did not fix the issue.

**Comment by Conal-Tuohy** [comment]
Where did the file come from originally, @sophlew ? Had the transcription been edited since it was first imported? I hope so, because it shouldn't be possible to have an undefined character entity otherwise.

**Comment by sophlew** [comment]
@Conal-Tuohy The manuscript was added to Nyingarn as images for OCR. In the new updates helping the users see errors in the TEI documents, I found this issue. The OCR had transcribed the symbol >. I deleted it because of the error message and clicked on the > markup button. Error mentioned above is still there. I've tracked the issue via screenshots
<img width="1239" alt="Screenshot 2023-04-18 at 6 40 38 pm" src="https://user-images.githubusercontent.com/91518014/232722726-3641e3c1-f5b2-4355-a972-8dec56d4287c.png">
<img width="1237" alt="Screenshot 2023-04-18 at 6 40 51 pm" src="https://user-images.githubusercontent.com/91518014/232722757-947500f5-534d-4368-b948-3762a7799f4d.png">
<img width="1244" alt="Screenshot 2023-04-18 at 6 41 00 pm" src="https://user-images.githubusercontent.com/91518014/232722782-5eed67e1-a27b-42f2-ad6a-9e7aaf7ba90d.png">
<img width="1248" alt="Screenshot 2023-04-18 at 6 41 07 pm" src="https://user-images.githubusercontent.com/91518014/232722823-87e7ffe8-3215-4d83-8135-a7d2796c3ab8.png">

**Comment by Conal-Tuohy** [comment]
It looks like the `>` character has been imported as `rt` when it should be `gt` ("**g**reater **t**han"). Perhaps just a typo in the OCR import pipeline?

**Comment by sophlew** [comment]
Thanks @Conal-Tuohy. Could we fix it next week please? There are a number of items affected by this issue.

**Comment by Conal-Tuohy** [comment]
this is fixed in #171

**Comment by sophlew** [comment]
I checked this issue after today's release, and it is still not working. The same error is coming up - please see screenshot 
![Screenshot 2023-05-01 at 2 54 18 pm](https://user-images.githubusercontent.com/91518014/235408753-c34e1274-f2e6-4a65-a76b-ea81283dd6ab.png) @Conal-Tuohy

**Comment by marcolarosa** [comment]
I've just applied the fix for this.

@Conal-Tuohy was correct in his fix in the transcription pipeline but that doesn't apply to the UI controls. They are driven by the configuration and the wrong element was there as well.

Try again and it should be ok. If not, reload the page then try.

**Comment by sophlew** [comment]
It worked, thanks
